/* INVOICES */
export const FETCH_INVOICES           = 'FETCH_INVOICES';
export const NEW_INVOICE              = 'NEW_INVOICE';
export const ADD_INVOICE_LINE_ITEM    = 'ADD_INVOICE_LINE_ITEM';
export const REMOVE_INVOICE_LINE_ITEM = 'REMOVE_INVOICE_LINE_ITEM';
export const CREATE_INVOICE           = 'CREATE_INVOICE';

/* PRODUCTS */
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const NEW_PRODUCT    = 'NEW_PRODUCT';
export const CHANGE_PRODUCT_ATTRIBUTES    = 'CHANGE_PRODUCT_ATTRIBUTES';
